import { NextResponse } from 'next/server'

export async function POST(req: Request) {
  try {
    const { report } = await req.json()
    if (!report) return NextResponse.json({ error: 'No report' }, { status: 400 })

    // Usa docx-js per generare DOCX con hyperlink reali
    const {
      Document, Packer, Paragraph, TextRun, ExternalHyperlink,
      HeadingLevel, AlignmentType, LevelFormat, UnderlineType,
    } = await import('docx')

    const today = new Date().toLocaleDateString('en-US', {
      weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
    })

    const children: any[] = []

    // Titolo
    children.push(new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [new TextRun({ text: 'ForwardAlpha Daily Market Briefing', color: 'E97316', bold: true, size: 36 })]
    }))
    children.push(new Paragraph({
      children: [new TextRun({ text: today, color: '666666', size: 20 })]
    }))
    children.push(new Paragraph({ children: [new TextRun('')] }))

    // Processa ogni riga del report
    const lines = report.split('\n')
    for (const line of lines) {
      if (line.trim() === '') {
        children.push(new Paragraph({ children: [new TextRun('')] }))
        continue
      }

      // Sezione heading (**TESTO**)
      if (line.startsWith('**') && line.endsWith('**')) {
        const text = line.replace(/\*\*/g, '')
        children.push(new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun({ text, color: 'E97316', bold: true, size: 26 })]
        }))
        continue
      }

      // Link articolo (📰 https://...)
      const articleMatch = line.match(/^\s*📰\s*(https?:\/\/\S+)/)
      if (articleMatch) {
        children.push(new Paragraph({
          indent: { left: 720 },
          children: [
            new TextRun({ text: '📰 ', size: 18 }),
            new ExternalHyperlink({
              link: articleMatch[1],
              children: [new TextRun({ text: 'Read article', color: '2563EB', underline: { type: UnderlineType.SINGLE }, size: 18 })]
            })
          ]
        }))
        continue
      }

      // Stock page (📊 TICKER → https://...)
      const stockMatch = line.match(/^\s*📊\s*([A-Z0-9]+)\s*→\s*(https?:\/\/\S+)/)
      if (stockMatch) {
        children.push(new Paragraph({
          indent: { left: 720 },
          children: [
            new TextRun({ text: '📊 ', size: 18 }),
            new ExternalHyperlink({
              link: stockMatch[2],
              children: [new TextRun({ text: stockMatch[1] + ' — Stock page', color: 'E97316', underline: { type: UnderlineType.SINGLE }, bold: true, size: 18 })]
            })
          ]
        }))
        continue
      }

      // Riga bullet (•)
      if (line.startsWith('•')) {
        const text = line.slice(1).trim()
        // Processa **bold** inline
        const parts = text.split('**')
        const runs = parts.map((part: string, i: number) =>
          new TextRun({ text: part, bold: i % 2 === 1, size: 22 })
        )
        children.push(new Paragraph({
          indent: { left: 360, hanging: 360 },
          children: [new TextRun({ text: '• ', size: 22 }), ...runs]
        }))
        continue
      }

      // Riga normale con eventuale **bold**
      const parts = line.split('**')
      const runs = parts.map((part: string, i: number) =>
        new TextRun({ text: part, bold: i % 2 === 1, size: 22, color: i % 2 === 1 ? 'E97316' : '000000' })
      )
      children.push(new Paragraph({ children: runs }))
    }

    // Footer ForwardAlpha
    children.push(new Paragraph({ children: [new TextRun('')] }))
    children.push(new Paragraph({
      children: [new TextRun({ text: 'Generated by ForwardAlpha — forwardalpha.pro', color: '999999', size: 18, italics: true })]
    }))

    const doc = new Document({
      styles: {
        default: { document: { run: { font: 'Calibri', size: 22 } } },
        paragraphStyles: [
          { id: 'Heading1', name: 'Heading 1', basedOn: 'Normal', next: 'Normal', quickFormat: true,
            run: { size: 36, bold: true, font: 'Calibri' },
            paragraph: { spacing: { before: 240, after: 120 }, outlineLevel: 0 } },
          { id: 'Heading2', name: 'Heading 2', basedOn: 'Normal', next: 'Normal', quickFormat: true,
            run: { size: 26, bold: true, font: 'Calibri' },
            paragraph: { spacing: { before: 200, after: 100 }, outlineLevel: 1 } },
        ]
      },
      sections: [{
        properties: {
          page: { size: { width: 11906, height: 16838 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } }
        },
        children
      }]
    })

    const buffer = await Packer.toBuffer(doc)
    const uint8 = new Uint8Array(buffer)
    return new NextResponse(uint8, {
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'Content-Disposition': `attachment; filename="ForwardAlpha_Report_${new Date().toISOString().slice(0,10)}.docx"`,
      }
    })
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 })
  }
}
